name: watermark
description: watermark image demo project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: 8.1.2
  equatable: 2.0.5

  image: 4.0.17
  image_picker: 0.8.7+4
  path_provider: 2.0.15
  permission_handler: 10.2.0
  flutter_image_compress: 2.0.1
  photo_view: 0.14.0
  photo_manager: 2.6.0
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
